name: Fetch/Update Xenia Game Patches from GitHub API

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering
  
env:
  XENIA_CANARY_REPO: xenia-canary/game-patches
  XENIA_NETPLAY_REPO: AdrianCassar/Xenia-WebServices

jobs:
  fetch-xenia-game-patches:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        sparse-checkout: |
          Database/
        sparse-checkout-cone-mode: false
        
    - name: Create required directories
      run: |
        mkdir -p Database/Patches
        
    - name: Fetch Xenia Canary Game Patches
      id: fetch-canary-patches
      run: |
        echo "Fetching Xenia Canary patches..."
        HTTP_STATUS=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "User-Agent: GitHub-Actions-Bot" \
          -o Database/Patches/canary_patches.json \
          -s -w "%{http_code}" \
          "https://api.github.com/repos/${{ env.XENIA_CANARY_REPO }}/contents/patches")
        
        echo "HTTP Status: $HTTP_STATUS"
        
        if [ "$HTTP_STATUS" -eq 200 ]; then
          echo "✓ Successfully fetched Xenia Canary patches"
          echo "canary_success=true" >> $GITHUB_OUTPUT
        else
          echo "✗ Failed to fetch Xenia Canary patches: HTTP $HTTP_STATUS"
          echo "canary_success=false" >> $GITHUB_OUTPUT
          # Don't exit here, continue with other patches
        fi
        
    - name: Fetch Xenia Netplay Game Patches  
      id: fetch-netplay-patches
      run: |
        echo "Fetching Xenia Netplay patches..."
        HTTP_STATUS=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "User-Agent: GitHub-Actions-Bot" \
          -o Database/Patches/netplay_patches.json \
          -s -w "%{http_code}" \
          "https://api.github.com/repos/${{ env.XENIA_NETPLAY_REPO }}/contents/patches")
        
        echo "HTTP Status: $HTTP_STATUS"
        
        if [ "$HTTP_STATUS" -eq 200 ]; then
          echo "✓ Successfully fetched Xenia Netplay patches"
          echo "netplay_success=true" >> $GITHUB_OUTPUT
        else
          echo "✗ Failed to fetch Xenia Netplay patches: HTTP $HTTP_STATUS"
          echo "netplay_success=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Validate JSON files
      id: validate
      run: |
        validation_failed=false
        
        if [ "${{ steps.fetch-canary-patches.outputs.canary_success }}" = "true" ]; then
          if jq . Database/Patches/canary_patches.json > /dev/null 2>&1; then
            echo "✓ Canary patches JSON is valid"
          else
            echo "✗ Canary patches JSON is invalid"
            validation_failed=true
          fi
        fi
        
        if [ "${{ steps.fetch-netplay-patches.outputs.netplay_success }}" = "true" ]; then
          if jq . Database/Patches/netplay_patches.json > /dev/null 2>&1; then
            echo "✓ Netplay patches JSON is valid"
          else
            echo "✗ Netplay patches JSON is invalid"
            validation_failed=true
          fi
        fi
        
        if [ "$validation_failed" = "true" ]; then
          echo "JSON validation failed"
          exit 1
        fi
        
    - name: Check for changes
      id: check-changes
      run: |
        if git diff --quiet Database/Patches/; then
          echo "No changes detected in patches"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected in patches"
          echo "has_changes=true" >> $GITHUB_OUTPUT
          
          # Show what changed
          echo "Changed files:"
          git diff --name-only Database/Patches/
        fi
        
    - name: Generate summary
      run: |
        echo "## Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Source | Status | File Size |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|--------|-----------|" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.fetch-canary-patches.outputs.canary_success }}" = "true" ]; then
          canary_size=$(stat -c%s Database/Patches/canary_patches.json 2>/dev/null || echo "0")
          echo "| Xenia Canary | ✅ Success | ${canary_size} bytes |" >> $GITHUB_STEP_SUMMARY
        else
          echo "| Xenia Canary | ❌ Failed | - |" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ steps.fetch-netplay-patches.outputs.netplay_success }}" = "true" ]; then
          netplay_size=$(stat -c%s Database/Patches/netplay_patches.json 2>/dev/null || echo "0")
          echo "| Xenia Netplay | ✅ Success | ${netplay_size} bytes |" >> $GITHUB_STEP_SUMMARY
        else
          echo "| Xenia Netplay | ❌ Failed | - |" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Changes detected:** ${{ steps.check-changes.outputs.has_changes }}" >> $GITHUB_STEP_SUMMARY
        
    - name: Commit and push changes
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        # Configure git
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Add files that were successfully fetched
        if [ "${{ steps.fetch-canary-patches.outputs.canary_success }}" = "true" ]; then
          git add Database/Patches/canary_patches.json
        fi
        
        if [ "${{ steps.fetch-netplay-patches.outputs.netplay_success }}" = "true" ]; then
          git add Database/Patches/netplay_patches.json
        fi
        
        # Create detailed commit message
        commit_msg="Update game patches - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        
        if [ "${{ steps.fetch-canary-patches.outputs.canary_success }}" = "true" ] && [ "${{ steps.fetch-netplay-patches.outputs.netplay_success }}" = "true" ]; then
          commit_msg="$commit_msg

        - Updated Xenia Canary patches
        - Updated Xenia Netplay patches"
        elif [ "${{ steps.fetch-canary-patches.outputs.canary_success }}" = "true" ]; then
          commit_msg="$commit_msg

        - Updated Xenia Canary patches
        - Xenia Netplay patches update failed"
        elif [ "${{ steps.fetch-netplay-patches.outputs.netplay_success }}" = "true" ]; then
          commit_msg="$commit_msg

        - Xenia Canary patches update failed  
        - Updated Xenia Netplay patches"
        fi
        
        # Commit and push
        git commit -m "$commit_msg"
        git push
        
        echo "✓ Changes committed and pushed successfully"