name: Database Updater

on:
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC
    - cron: '0 12 * * *'  # daily at 12:00 UTC
  workflow_dispatch:
  
env:
  XENIA_CANARY_REPO: xenia-canary/game-patches
  XENIA_NETPLAY_REPO: AdrianCassar/Xenia-WebServices

jobs:
  update-database:
    name: Update Database
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
          sparse-checkout: |
            data/patches/canary.json
            data/patches/canary.tmp
            data/patches/netplay.json
            data/patches/netplay.tmp
            data/game-compatibility/stable.json
            data/game-compatibility/canary.json
            data/version.json
            scripts/game_compatibility.py
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Fetch Xenia Manager versions
        id: fetch-versions
        env:
          AUTH_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          cat > fetch_versions.py << 'EOF'
          import json
          import urllib.request
          import urllib.error
          import os
          import sys
          def fetch_version(url, name):
              try:
                  headers = {
                      'User-Agent': 'github-actions',
                      'Accept': 'application/vnd.github+json'
                  }
                  token = os.environ.get("AUTH_TOKEN")
                  if token:
                      headers['Authorization'] = f"Bearer {token}"
                  req = urllib.request.Request(url, headers=headers)
                  with urllib.request.urlopen(req, timeout=10) as response:
                      data = json.loads(response.read())
                      return data.get('tag_name', 'unknown')
              except (urllib.error.URLError, json.JSONDecodeError, KeyError) as e:
                  print(f"Error fetching {name}: {e}", file=sys.stderr)
                  return 'unknown'
          urls = {
              'stable': 'https://api.github.com/repos/xenia-manager/xenia-manager/releases/latest',
              'experimental': 'https://api.github.com/repos/xenia-manager/experimental-builds/releases/latest'
          }
          data = {key: fetch_version(url, key) for key, url in urls.items()}
          with open('data/version.json', 'w', encoding='utf-8') as f:
              json.dump(data, f, indent=2)
          print("Versions fetched successfully")
          EOF
          python fetch_versions.py
      - name: Update game compatibility database (Canary)
        run: python scripts/game_compatibility.py --complete --debug
        env:
          TOKEN: ${{ secrets.COMMIT_TOKEN }}

      - name: Update game compatibility database (Stable)
        if: github.event_name == 'workflow_dispatch'
        run: python scripts/game_compatibility.py --stable --complete --debug
        env:
          TOKEN: ${{ secrets.COMMIT_TOKEN }}

      - name: Fetch game patches
        id: fetch-patches
        env:
          AUTH_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          fetch_with_retry() {
            local url=$1
            local output=$2
            local name=$3
            local max_attempts=3
            local attempt=1
            local temp_file="${output}.tmp"
            while [ $attempt -le $max_attempts ]; do
              echo "Fetching $name (attempt $attempt/$max_attempts)..."
              status=$(curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "User-Agent: GitHub-Actions-Bot" \
                -H "Authorization: Bearer ${AUTH_TOKEN}" \
                -o "$temp_file" \
                -s -w "%{http_code}" \
                --max-time 30 \
                --retry 2 \
                --retry-delay 5 \
                "$url")
              if [ "$status" -eq 200 ]; then
                if jq empty "$temp_file" 2>/dev/null; then
                  jq '.' "$temp_file" > "$output"
                  rm "$temp_file"
                  echo "$name fetched successfully"
                  echo "${name}_success=true" >> $GITHUB_OUTPUT
                  return 0
                else
                  echo "Invalid JSON in $name response"
                fi
              else
                echo "HTTP $status for $name"
              fi
              attempt=$((attempt + 1))
              [ $attempt -le $max_attempts ] && sleep 10
            done
            echo "${name}_success=false" >> $GITHUB_OUTPUT
            return 1
          }
          mkdir -p data/patches
          fetch_with_retry \
            "https://api.github.com/repos/${{ env.XENIA_CANARY_REPO }}/contents/patches" \
            "data/patches/canary.json" \
            "canary"
          fetch_with_retry \
            "https://api.github.com/repos/${{ env.XENIA_NETPLAY_REPO }}/contents/patches" \
            "data/patches/netplay.json" \
            "netplay"
      - name: Check for changes and commit
        id: check-changes
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          git config --global user.name 'xeniamanager-ci'
          git config --global user.email '214508751+xeniamanager-ci@users.noreply.github.com'
          git add data/
          if git diff --cached --quiet; then
            echo "No changes detected in any database files"
            echo "changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "changes=true" >> $GITHUB_OUTPUT
          changed_files=""
          updates=()
          if git diff --cached --name-only | grep -q "data/version.json"; then
            changed_files="$changed_files data/version.json"
            updates+=("Xenia Manager versions")
          fi
          if git diff --cached --name-only | grep -q "data/game-compatibility/canary.json"; then
            changed_files="$changed_files data/game-compatibility/canary.json"
            updates+=("Game compatibility database (Canary)")
          fi
          if git diff --cached --name-only | grep -q "data/game-compatibility/stable.json"; then
            changed_files="$changed_files data/game-compatibility/stable.json"
            updates+=("Game compatibility database (Stable)")
          fi
          if git diff --cached --name-only | grep -q "data/patches/"; then
            changed_files="$changed_files data/patches/"
            if [ "${{ steps.fetch-patches.outputs.canary_success }}" = "true" ] && [ "${{ steps.fetch-patches.outputs.netplay_success }}" = "true" ]; then
              updates+=("Xenia Canary & Netplay patches")
            elif [ "${{ steps.fetch-patches.outputs.canary_success }}" = "true" ]; then
              updates+=("Xenia Canary patches")
            elif [ "${{ steps.fetch-patches.outputs.netplay_success }}" = "true" ]; then
              updates+=("Xenia Netplay patches")
            fi
          fi
          timestamp=$(date -u '+%Y-%m-%d %H:%M:%S')
          if [ ${#updates[@]} -eq 1 ]; then
            commit_msg="Update ${updates[0]} - $timestamp UTC"
          else
            commit_msg="Update database - $timestamp UTC"
            for update in "${updates[@]}"; do
              commit_msg="$commit_msg"$'\n- '"$update"
            done
          fi
          echo "Committing changes:"
          git diff --stat --cached
          git commit -m "$commit_msg"
          git push
          echo "Successfully committed and pushed changes"