name: Update Launchbox Metadata

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Database Updater"]
    types:
      - completed

jobs:
  update_launchbox_metadata:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Update Launchbox Database Metadata
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            data/metadata/launchbox/games.json
            data/metadata/launchbox/search.json
            data/metadata/launchbox/titles/
            scripts/launchbox_metadata.py
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Download Metadata
        shell: pwsh
        run: Invoke-WebRequest -Uri "https://gamesdb.launchbox-app.com/Metadata.zip" -OutFile "Metadata.zip"

      - name: Extract Metadata
        shell: pwsh
        run: Expand-Archive -Path "Metadata.zip" -DestinationPath "Metadata" -Force

      - name: Parse Metadata
        run: python scripts/launchbox_metadata.py --debug

      - name: Cleanup temporary files
        shell: pwsh
        run: |
          Remove-Item -Path "Metadata.zip" -Force
          Remove-Item -Path "Metadata" -Recurse -Force

      - name: Commit and push changes
        shell: pwsh
        run: |
          git config --global user.name "xeniamanager-ci"
          git config --global user.email "214508751+xeniamanager-ci@users.noreply.github.com"
          git add data/metadata/launchbox/
          if (-not (git diff --cached --quiet)) {
            git commit -m "chore: Update Launchbox Metadata"
            git pull --rebase origin feat/launchbox-support
            git push
          }